spring:
    # 引擎模板配置
    thymeleaf:
        cache: false # 关闭缓存
        mode: LEGACYHTML5 # 去除htm5严格校验
        prefix: classpath:/templates/ # 指定 thymeleaf 模板路径
        encoding: UTF-8 # 指定字符集编码
    
    #数据源配置
    datasource:
        url: jdbc:mysql://c001:3306/demo?useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: admin
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        
    redis:
        timeout: 6000ms
        database: 10 
        host: c001 #单实例redis用这个配置
        password: 111111
        port: 6379 
        lettuce:
            pool: 
                max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
                max-idle: 10 #连接池中的最大空闲连接
                min-idle: 3 #连接池中的最小空闲连接
                max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）